config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :articles
  root 'pages#index'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/article.rb
class Article < ActiveRecord::Base
  has_attached_file :photo, :styles => { :large => '500x500>',:medium => "200x200>", :thumb => "50x50#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :authenticate_admin!,except: [:index,:show]
	before_action :find_article,only: [:show,:edit,:update,:destroy]

	def index
		@articles = Article.all.order(created_at: :desc)
	end

	def show
		# @random = Article.all.order("RAND()").first
	end

	def new
		@article = Article.new
	end

	def create
		@article = Article.create(article_params)
		redirect_to article_path(@article)
	end

	def edit
	end

	def update
		if @article.update(article_params)
			respond_to do |format|
				format.html{ redirect_to article_path(@article) }
				format.js 
			end
		else
			render 'edit'
		end
	end

	def destroy
		if @article.destroy
			respond_to do |format|
				format.html{ redirect_to root_path }
				format.js
			end
		end
	end

	private
		def find_article
			@article = Article.find(params[:id])
		end

		def article_params
			params.require(:article).permit(:story,:photo)
		end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def index
		@newsletter = Article.new()
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.haml
.article.panel.panel-default{data:{id: article.id}}
	.row
		.col-md-10
			%p.image
				= link_to (image_tag article.photo.url(:medium),class: 'img-rounded img-responsive'),article_path(article)
			%p.story
				= article.story
		- if admin_signed_in?
			.col-md-2
				= link_to "Delete",article_path(article),method: :delete,data:{confirm: "Are you sure??"},class: 'btn btn-default btn-delete',remote: true

app/views/articles/_form.html.haml
= simple_form_for @article,html:{multipart: true} do |f|
	.form-group
		= f.input :photo,input_html:{class: 'form-control dropzone'}
	.form-group
		= f.input :story,label: false,input_html:{class: 'form-control',placeholder: 'Story'}
	.form-group
		= f.submit "Create story",class: 'btn btn-default'

app/views/articles/edit.html.haml
.article.center
	= image_tag @article.photo.url(:medium),class: 'panel'
	= render 'form'

app/views/articles/index.html.haml
.parent.center
	= render partial: 'article',collection: @articles

app/views/articles/new.html.haml
.article-form.center
	= render 'form'

app/views/articles/show.html.haml
.row
	.col-md-10.col-md-offset-1
		.article.center.panel.panel-default
			= image_tag @article.photo.url(:large),class: 'image img-responsive'
			%hr
			%p.story
				= @article.story
		- if admin_signed_in?
			%hr
				= link_to "Edit",edit_article_path(@article),class: 'btn btn-default'
				= link_to "Delete",article_path(@article),method: :delete,data:{confirm: "Are you sure??"},class: 'btn btn-default'
	/ .col-xs-2
	/ 	%h3 Random Scrap
	/ 	%hr
	/ 	.random.center.panel.panel-default
	/ 		.photo.center
	/ 			= image_tag @random.photo.url(:medium),class: 'panel'
	/ 		%hr
	/ 		%p.story
	/ 			= truncate @article.story, length: 160
	/ 	%hr

app/views/layouts/application.html.haml
!!! 5
%html
%head
	%title Scrap
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
	= stylesheet_link_tag    'http://fonts.googleapis.com/css?family=Open+Sans', media: 'all', 'data-turbolinks-track' => true 
	= javascript_include_tag 'application', 'data-turbolinks-track' => true
	= csrf_meta_tags 
%body
	%nav.navbar.navbar-default.navbar-fixed-top
		.container-fluid 
			.brand.center
				= link_to "Scrap",root_path,class: 'logo'
			%ul.nav.navbar-nav.navbar-right
				-if admin_signed_in?
					%li.dropdown
						%a{:href => "#", :class => "dropdown-toggle", :role =>"button",:data => {:toggle => "dropdown"}}
							%i.fa.fa-bars 
								&nbsp;
								= current_admin.email
						%ul.dropdown-menu{:role=>'menu'}
							%li
								= link_to "Articles",articles_path
							%li 
								= link_to "Edit Profile",edit_admin_registration_path
							%li 
								= link_to "Create Article",new_article_path
							%li.divider
							%li
								= link_to "Sign out", destroy_admin_session_path, method: :delete
				-else
					%li
						= link_to "Sign in",new_admin_session_path
					%li
						= link_to "Sign up",new_admin_registration_path 
	.container
		= yield 

app/views/pages/index.html.haml
.center.subscribe
	%h2.brand
		Scrap.in
	%hr
	= link_to "Signup for Newsletters",root_path,class: 'btn btn-default btn-custom signup-newsletter-btn'
	%input{type: "text",class: 'form-control newsletter-field',id: 'newsletter'}
	%br
	%span.hint
		We won't spam you :)